server:
  port: 8051
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: ftp-demo

  datasource:
    url: jdbc:mysql://localhost:3306/ftpdemo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: thingsmatrix@8
    initialization-mode: always
  jpa:
    database: mysql
    database-platform: com.example.ftpdemo.config.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC


logging:
  file.max-size: 1024MB
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
    com.thingsmatrix: DEBUG
    software.amazon: DEBUG
  register-shutdown-hook: false
  file:
    name: /applogs/backend/${spring.application.name}.log
ftp:
  server:
    port: 3132
    passive-ports: "10000-10005"
  user:
    root-dir: "/ftp/"


